FROM python:3.8-slim

COPY . /songmoana
WORKDIR /songmoana

RUN apt update && apt install -y screen libgl1-mesa-glx
RUN apt-get install -y --no-install-recommends software-properties-common gcc g++ gfortran pkg-config
RUN apt-get install -y --no-install-recommends libopenblas-dev libatlas-base-dev liblapack-dev ccache

RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements_sift.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]